### ISSUE TITLE
 Azure CLI install never worked on macOS

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#743]
A mac user had to do the manual install process, and the Azure CLI install never worked.  It was missing the packages needed to login, etc.

```
Last login: Sat Jan 27 10:53:09 on ttys000
Daves-MacBook-Pro:~ dave$ cd ~/Docu
-bash: cd: /Users/dave/Docu: No such file or directory
Daves-MacBook-Pro:~ dave$ cd ~/Documents
Daves-MacBook-Pro:Documents dave$ ls -la
total 64
drwxr-xr-x@  3 dave  staff     96 Jul 19  2016 $RECYCLE.BIN
drwxr-xr-x+ 17 dave  staff    544 Jan 27 09:57 .
drwxr-xr-x+ 58 dave  staff   1856 Jan 27 10:54 ..
-rw-r--r--@  1 dave  staff  26628 Jan 27 09:59 .DS_Store
-rw-------   1 dave  staff      0 Jul  3  2016 .localized
drwxrwxrwx   6 dave  staff    192 Jan 27 09:59 AzureIoTWorkshop
drwxr-xr-x   5 dave  staff    160 Jan 12 07:47 Backgrounds
drwxr-xr-x  71 dave  staff   2272 Dec 20 10:35 Consulting Resources
drwxr-xr-x   9 dave  staff    288 Dec 18 12:39 Continuous Delivery
drwxr-xr-x  13 dave  staff    416 Jan 12 07:14 LeadingAgile
drwxr-xr-x   6 dave  staff    192 Mar 30  2017 Metrics
drwxr-xr-x   7 dave  staff    224 Jan 17  2017 MuseScore2
drwxr-xr-x  13 dave  staff    416 Jan 12 07:14 Personal
drwxr-xr-x  70 dave  staff   2240 Jan 13 20:20 Projects
drwxr-xr-x  20 dave  staff    640 Jan 12 07:11 Software
drwxr-xr-x@  8 dave  staff    256 Oct 24 09:46 Virtual Machines.localized
-rw-r--r--@  1 dave  staff    315 Jan 27 09:57 iot-azure-notes.txt
Daves-MacBook-Pro:Documents dave$ cd AzureIoTWorkshop/
Daves-MacBook-Pro:AzureIoTWorkshop dave$ cd DevKit
Daves-MacBook-Pro:DevKit dave$ ls -la
total 24
drwxrwxrwx  5 dave  staff   160 Jan 27 09:59 .
drwxrwxrwx  6 dave  staff   192 Jan 27 09:59 ..
-rw-r--r--@ 1 dave  staff  8196 Jan 27 09:59 .DS_Store
drwxrwxrwx  8 dave  staff   256 Jan 27 09:28 devkit_install_mac_1.3.1.42
drwxrwxrwx  8 dave  staff   256 Jan 27 09:28 devkit_install_win_1.3.1.42
Daves-MacBook-Pro:DevKit dave$ cd devkit_install_mac_1.3.1.42/
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ brew install arduino
Error: No available formula with the name "arduino" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ brew cask reinstall --force arduino
==> Creating Caskroom at /usr/local/Caskroom
==> We'll set permissions properly so we won't need sudo in the future
Password:
==> Caveats
arduino requires Java. You can install the latest version with

  brew cask install java

==> Satisfying dependencies
==> Downloading https://downloads.arduino.cc/arduino-1.8.5-macosx.zip
######################################################################## 100.0%
==> Verifying checksum for Cask arduino
==> Installing Cask arduino
==> Moving App 'Arduino.app' to '/Applications/Arduino.app'.
==> Linking Binary 'arduino-builder' to '/usr/local/bin/arduino-builder'.
馃嵑  arduino was successfully installed!
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ ./install.sh

Updaing brew package list...

==> Reinstalling yarn 
==> Downloading https://yarnpkg.com/downloads/1.3.2/yarn-v1.3.2.tar.gz
Already downloaded: /Users/dave/Library/Caches/Homebrew/yarn-1.3.2.tar.gz
馃嵑  /usr/local/Cellar/yarn/1.3.2: 14 files, 3.9MB, built in 1 second
yarn install v1.3.2
info No lockfile found.
[1/4] 馃攳  Resolving packages...
warning azure-event-hubs > azure-iot-common > crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning run-sequence > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning babel-preset-es2015@6.24.1: 馃檶  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning gulp-watch > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] 馃殮  Fetching packages...
[3/4] 馃敆  Linking dependencies...
[4/4] 馃搩  Building fresh packages...
error /Users/dave/azure-board-cli/node_modules/serialport: Command failed.
Exit code: 127
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /Users/dave/azure-board-cli/node_modules/serialport
Output:
prebuild-install info begin Prebuild-install version 2.5.0
prebuild-install info looking for local prebuild @ prebuilds/serialport-v6.0.4-node-v59-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/dave/.npm/_prebuilds/https-github.com-EmergingTechnologyAdvisors-node-serialport-releases-download-v6.0.4-serialport-v6.0.4-node-v59-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/v6.0.4/serialport-v6.0.4-node-v59-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/v6.0.4/serialport-v6.0.4-node-v59-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.4.0 runtime=node arch=x64 platform=darwin)
/bin/sh: node-gyp: command not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  - Checking pre-conditions of task: Install Arduino
|   V Install Arduino: 1.8.5
  - Checking pre-conditions of task: Install ST Link
|   V Install ST Link: installed
  - Checking pre-conditions of task: Set Custom Board Manager URL
\   V Set Custom Board Manager URL: done
  - Checking pre-conditions of task: Install Board Package
\   V Install Board Package: installed
  - Checking pre-conditions of task: Install VS Code
/   V Install VS Code: installed
  - Checking pre-conditions of task: Install Arduino Extension
\   V Install Arduino Extension: installed
  - Checking pre-conditions of task: Generate platform.local.txt
? 
Microsoft would like to collect data about how users use Azure IoT DevKit and so
me problems they encounter. Microsoft uses this information to improve our DevKi
t experience. Participation is voluntary and when you choose to participate your
 device automatically sends information to Microsoft about how you use Azure IoT
 DevKit. 

Select Y to enable data collection :(Y/n, default is Y)  Yes
\   V Generate platform.local.txt: platform.local.txt generated successfully
  - Checking pre-conditions of task: Check Arduino Package
/   V Check Arduino Package: done
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ ./install.sh

Updaing brew package list...

==> Reinstalling yarn 
==> Downloading https://yarnpkg.com/downloads/1.3.2/yarn-v1.3.2.tar.gz
Already downloaded: /Users/dave/Library/Caches/Homebrew/yarn-1.3.2.tar.gz
馃嵑  /usr/local/Cellar/yarn/1.3.2: 14 files, 3.9MB, built in 1 second
yarn install v1.3.2
info No lockfile found.
[1/4] 馃攳  Resolving packages...
warning azure-event-hubs > azure-iot-common > crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning run-sequence > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning babel-preset-es2015@6.24.1: 馃檶  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning gulp-watch > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] 馃殮  Fetching packages...
[3/4] 馃敆  Linking dependencies...
[4/4] 馃搩  Building fresh packages...
error /Users/dave/azure-board-cli/node_modules/serialport: Command failed.
Exit code: 127
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /Users/dave/azure-board-cli/node_modules/serialport
Output:
prebuild-install info begin Prebuild-install version 2.5.0
prebuild-install info looking for local prebuild @ prebuilds/serialport-v6.0.4-node-v59-darwin-x64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/dave/.npm/_prebuilds/https-github.com-EmergingTechnologyAdvisors-node-serialport-releases-download-v6.0.4-serialport-v6.0.4-node-v59-darwin-x64.tar.gz
prebuild-install http request GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/v6.0.4/serialport-v6.0.4-node-v59-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/v6.0.4/serialport-v6.0.4-node-v59-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.4.0 runtime=node arch=x64 platform=darwin)
/bin/sh: node-gyp: command not found
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
  - Checking pre-conditions of task: Install ST Link
\   V Install ST Link: installed
  - Checking pre-conditions of task: Set Custom Board Manager URL
|   V Set Custom Board Manager URL: done
  - Checking pre-conditions of task: Install Board Package
  X installBoardPackage: Unexpected error when executing "" --install-boards AZ3166:stm32f4:1.3.1 : Command failed: "" --install-boards AZ3166:stm32f4:1.3.1
/bin/sh: : command not found
. Error: Command failed: "" --install-boards AZ3166:stm32f4:1.3.1
/bin/sh: : command not found

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ ls -la
total 32
drwxrwxrwx   8 dave  staff   256 Jan 27 09:28 .
drwxrwxrwx   5 dave  staff   160 Jan 27 09:59 ..
-rwxrwxrwx   1 dave  staff   150 Jan 27 08:20 .babelrc
-rwxrwxrwx   1 dave  staff  1676 Jan 27 08:20 gulpfile.js
-rwxrwxrwx   1 dave  staff  2990 Jan 27 10:28 install.sh
drwxrwxrwx  14 dave  staff   448 Jan 27 09:28 out
-rwxrwxrwx   1 dave  staff  1657 Jan 27 08:20 package.json
drwxrwxrwx   4 dave  staff   128 Jan 27 09:28 tools
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ cd tools
Daves-MacBook-Pro:tools dave$ ls -la
total 0
drwxrwxrwx  4 dave  staff  128 Jan 27 09:28 .
drwxrwxrwx  8 dave  staff  256 Jan 27 09:28 ..
drwxrwxrwx  5 dave  staff  160 Jan 27 09:28 darwin
drwxrwxrwx  5 dave  staff  160 Jan 27 09:28 staging
Daves-MacBook-Pro:tools dave$ cd darwin
Daves-MacBook-Pro:darwin dave$ ls -la
total 888
drwxrwxrwx  5 dave  staff     160 Jan 27 09:28 .
drwxrwxrwx  4 dave  staff     128 Jan 27 09:28 ..
-rwxrwxrwx  1 dave  staff  140856 Jan 27 08:20 st-flash
-rwxrwxrwx  1 dave  staff  136544 Jan 27 08:20 st-info
-rwxrwxrwx  1 dave  staff  171636 Jan 27 08:20 st-util
Daves-MacBook-Pro:darwin dave$ cd ../..
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ cd
Daves-MacBook-Pro:~ dave$ az
Error loading command module 'dla'

Welcome to Azure CLI!
---------------------
Use `az -h` to see available commands or go to https://aka.ms/cli.

Telemetry
---------
The Azure CLI collects usage data in order to improve your experience.
The data is anonymous and does not include commandline argument values.
The data is collected by Microsoft.

You can change your telemetry settings with `az configure`.


     /\
    /  \    _____   _ _  ___ _
   / /\ \  |_  / | | | \'__/ _\
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|


Welcome to the cool new Azure CLI!

Here are the base commands:

    account          : Manage Azure subscription information.
    acr              : Manage Azure Container Registries.
    acs              : Manage Azure Container Services.
    ad               : Synchronize on-premises directories and manage Azure Active Directory
                       resources.
    advisor          : (PREVIEW) Manage Azure Advisor.
    aks              : Manage Azure Kubernetes Services.
    appservice       : Manage App Service plans.
    backup           : Commands to manage Azure Backups.
    batch            : Manage Azure Batch.
    batchai          : Batch AI.
    billing          : Manage Azure Billing.
    cdn              : Manage Azure Content Delivery Networks (CDNs).
    cloud            : Manage registered Azure clouds.
    cognitiveservices: Manage Azure Cognitive Services accounts.
    configure        : Display and manage the Azure CLI 2.0 configuration. This command is
                       interactive.
    consumption      : Manage consumption of Azure resources.
    container        : (PREVIEW) Manage Azure Container Instances.
    cosmosdb         : Manage Azure Cosmos DB database accounts.
    disk             : Manage Azure Managed Disks.
    dls              : (PREVIEW) Manage Data Lake Store accounts and filesystems.
    eventgrid        : Manage Azure Event Grid topics and subscriptions.
    extension        : Manage and update CLI extensions.
    feature          : Manage resource provider features.
    feedback         : Loving or hating the CLI?  Let us know!
    find             : Find Azure CLI commands.
    functionapp      : Manage function apps.
    group            : Manage resource groups and template deployments.
    identity         : Managed Service Identities.
    image            : Manage custom virtual machine images.
    interactive      : Start interactive mode.
    iot              : (PREVIEW) Manage Internet of Things (IoT) assets.
    keyvault         : Safeguard and maintain control of keys, secrets, and certificates.
    lab              : Manage Azure DevTest Labs.
    lock             : Manage Azure locks.
    login            : Log in to Azure.
    logout           : Log out to remove access to Azure subscriptions.
    managedapp       : Manage template solutions provided and maintained by Independent Software
                       Vendors (ISVs).
    monitor          : Manage the Azure Monitor Service.
    mysql            : Manage Azure Database for MySQL servers.
    network          : Manage Azure Network resources.
    policy           : Manage resource policies.
    postgres         : Manage Azure Database for PostgreSQL servers.
    provider         : Manage resource providers.
    redis            : Access to a secure, dedicated Redis cache for your Azure applications.
    reservations     : Manage Azure Reservations.
    resource         : Manage Azure resources.
    role             : Manage user roles for access control with Azure Active Directory and service
                       principals.
    sf               : Manage and administer Azure Service Fabric clusters.
    snapshot         : Manage point-in-time copies of managed disks, native blobs, or other
                       snapshots.
    sql              : Manage Azure SQL Databases and Data Warehouses.
    storage          : Manage Azure Cloud Storage resources.
    tag              : Manage resource tags.
    vm               : Provision Linux or Windows virtual machines.
    vmss             : Manage groupings of virtual machines in an Azure Virtual Machine Scale Set
                       (VMSS).
    webapp           : Manage web apps.
Daves-MacBook-Pro:~ dave$ az --version
No module named 'pkg_resources'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/knack/cli.py", line 187, in invoke
    self.show_version()
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 79, in show_version
    print(get_az_version_string())
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/util.py", line 60, in get_az_version_string
    installed_dists = get_installed_cli_distributions()
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/util.py", line 51, in get_installed_cli_distributions
    from pkg_resources import working_set
ModuleNotFoundError: No module named 'pkg_resources'
Daves-MacBook-Pro:~ dave$ cd ~/Documents
Daves-MacBook-Pro:Documents dave$ cd AzureIoTWorkshop/
Daves-MacBook-Pro:AzureIoTWorkshop dave$ cd DevKit
Daves-MacBook-Pro:DevKit dave$ ls -la
total 24
drwxrwxrwx  5 dave  staff   160 Jan 27 09:59 .
drwxrwxrwx  6 dave  staff   192 Jan 27 09:59 ..
-rw-r--r--@ 1 dave  staff  8196 Jan 27 09:59 .DS_Store
drwxrwxrwx  8 dave  staff   256 Jan 27 09:28 devkit_install_mac_1.3.1.42
drwxrwxrwx  8 dave  staff   256 Jan 27 09:28 devkit_install_win_1.3.1.42
Daves-MacBook-Pro:DevKit dave$ cd devkit_install_mac_1.3.1.42/
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ ls -la
total 32
drwxrwxrwx   8 dave  staff   256 Jan 27 09:28 .
drwxrwxrwx   5 dave  staff   160 Jan 27 09:59 ..
-rwxrwxrwx   1 dave  staff   150 Jan 27 08:20 .babelrc
-rwxrwxrwx   1 dave  staff  1676 Jan 27 08:20 gulpfile.js
-rwxrwxrwx   1 dave  staff  2990 Jan 27 10:28 install.sh
drwxrwxrwx  14 dave  staff   448 Jan 27 09:28 out
-rwxrwxrwx   1 dave  staff  1657 Jan 27 08:20 package.json
drwxrwxrwx   4 dave  staff   128 Jan 27 09:28 tools
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ az
Error loading command module 'dla'

     /\
    /  \    _____   _ _  ___ _
   / /\ \  |_  / | | | \'__/ _\
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|


Welcome to the cool new Azure CLI!

Here are the base commands:

    account          : Manage Azure subscription information.
    acr              : Manage Azure Container Registries.
    acs              : Manage Azure Container Services.
    ad               : Synchronize on-premises directories and manage Azure Active Directory
                       resources.
    advisor          : (PREVIEW) Manage Azure Advisor.
    aks              : Manage Azure Kubernetes Services.
    appservice       : Manage App Service plans.
    backup           : Commands to manage Azure Backups.
    batch            : Manage Azure Batch.
    batchai          : Batch AI.
    billing          : Manage Azure Billing.
    cdn              : Manage Azure Content Delivery Networks (CDNs).
    cloud            : Manage registered Azure clouds.
    cognitiveservices: Manage Azure Cognitive Services accounts.
    configure        : Display and manage the Azure CLI 2.0 configuration. This command is
                       interactive.
    consumption      : Manage consumption of Azure resources.
    container        : (PREVIEW) Manage Azure Container Instances.
    cosmosdb         : Manage Azure Cosmos DB database accounts.
    disk             : Manage Azure Managed Disks.
    dls              : (PREVIEW) Manage Data Lake Store accounts and filesystems.
    eventgrid        : Manage Azure Event Grid topics and subscriptions.
    extension        : Manage and update CLI extensions.
    feature          : Manage resource provider features.
    feedback         : Loving or hating the CLI?  Let us know!
    find             : Find Azure CLI commands.
    functionapp      : Manage function apps.
    group            : Manage resource groups and template deployments.
    identity         : Managed Service Identities.
    image            : Manage custom virtual machine images.
    interactive      : Start interactive mode.
    iot              : (PREVIEW) Manage Internet of Things (IoT) assets.
    keyvault         : Safeguard and maintain control of keys, secrets, and certificates.
    lab              : Manage Azure DevTest Labs.
    lock             : Manage Azure locks.
    login            : Log in to Azure.
    logout           : Log out to remove access to Azure subscriptions.
    managedapp       : Manage template solutions provided and maintained by Independent Software
                       Vendors (ISVs).
    monitor          : Manage the Azure Monitor Service.
    mysql            : Manage Azure Database for MySQL servers.
    network          : Manage Azure Network resources.
    policy           : Manage resource policies.
    postgres         : Manage Azure Database for PostgreSQL servers.
    provider         : Manage resource providers.
    redis            : Access to a secure, dedicated Redis cache for your Azure applications.
    reservations     : Manage Azure Reservations.
    resource         : Manage Azure resources.
    role             : Manage user roles for access control with Azure Active Directory and service
                       principals.
    sf               : Manage and administer Azure Service Fabric clusters.
    snapshot         : Manage point-in-time copies of managed disks, native blobs, or other
                       snapshots.
    sql              : Manage Azure SQL Databases and Data Warehouses.
    storage          : Manage Azure Cloud Storage resources.
    tag              : Manage resource tags.
    vm               : Provision Linux or Windows virtual machines.
    vmss             : Manage groupings of virtual machines in an Azure Virtual Machine Scale Set
                       (VMSS).
    webapp           : Manage web apps.
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ az --version
No module named 'pkg_resources'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/knack/cli.py", line 187, in invoke
    self.show_version()
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 79, in show_version
    print(get_az_version_string())
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/util.py", line 60, in get_az_version_string
    installed_dists = get_installed_cli_distributions()
  File "/usr/local/Cellar/azure-cli/2.0.25/libexec/lib/python3.6/site-packages/azure/cli/core/util.py", line 51, in get_installed_cli_distributions
    from pkg_resources import working_set
ModuleNotFoundError: No module named 'pkg_resources'
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ azure-cli(2.0.20)
-bash: syntax error near unexpected token `2.0.20'
Daves-MacBook-Pro:devkit_install_mac_1.3.1.42 dave$ az login
Error loading command module 'dla'
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code F4HS47CN2 to authenticate.
```

**Comment by Sneezry** [comment]
Related issue on Azure CLI: https://github.com/Azure/azure-cli/issues/5503

**Comment by ihere1** [comment]
Close issue because it is a user environment problem. See how to fix at previous comment.
